// OpenCode Hook Integration Engine
//
// Generates opencode.json configuration with beforeRun/afterRun hooks
// that automatically load PCPM context before each OpenCode run and
// write back plan/memory updates after each run.
//
// This makes PCPM automatic rather than requiring manual CLI calls.
// The hooks work by:
//   beforeRun: inject active context (goal, plan, memory, session) into the prompt
//   afterRun:  extract knowledge from the completed session transcript
//
// Two integration modes:
//   1. "hooks" mode: generates shell scripts that the opencode hooks call
//   2. "config" mode: generates the opencode.json snippet to wire it up

import path from "node:path";

import { ensureDir, fileExists, readJsonFile, writeJsonFile } from "../lib/storage.js";

// Generate the beforeRun hook script content.
// This script runs before every opencode session and injects PCPM context.
// It calls `node <brain-cli> context` and writes the result to a temp file
// that gets prepended to the agent's system prompt.
function generateBeforeRunScript({ brainRepoPath, projectId, goalId, goalDescription }) {
  const cliPath = path.join(brainRepoPath, "src", "cli.js");

  return [
    "#!/usr/bin/env bash",
    "# PCPM beforeRun hook — auto-generated by global-brain hook-engine",
    "# Loads active context from the persistent brain and injects it",
    "# into the current OpenCode session as a system-level preamble.",
    "",
    `BRAIN_CLI="${cliPath}"`,
    `BRAIN_ROOT="${brainRepoPath}"`,
    `PROJECT_ID="${projectId}"`,
    `GOAL_ID="${goalId}"`,
    `GOAL_DESC="${goalDescription}"`,
    "",
    "# Generate active context JSON and write to temp file",
    'CONTEXT_FILE="/tmp/pcpm-context-${PROJECT_ID}.json"',
    "",
    'node "$BRAIN_CLI" context \\',
    '  --root "$BRAIN_ROOT" \\',
    '  --project "$PROJECT_ID" \\',
    '  --goal-id "$GOAL_ID" \\',
    '  --description "$GOAL_DESC" \\',
    '  > "$CONTEXT_FILE" 2>/dev/null',
    "",
    "# If context generation succeeded, output it as system context",
    'if [ -f "$CONTEXT_FILE" ] && [ -s "$CONTEXT_FILE" ]; then',
    '  echo "PCPM_CONTEXT_LOADED=true"',
    '  cat "$CONTEXT_FILE"',
    "fi",
    ""
  ].join("\n");
}

// Generate the afterRun hook script content.
// This script runs after every opencode session and extracts knowledge
// from the session transcript back into the brain.
function generateAfterRunScript({ brainRepoPath, projectId, sessionId }) {
  const cliPath = path.join(brainRepoPath, "src", "cli.js");

  return [
    "#!/usr/bin/env bash",
    "# PCPM afterRun hook — auto-generated by global-brain hook-engine",
    "# Extracts knowledge from the completed session transcript and",
    "# writes it back into the persistent brain stores.",
    "# ALSO runs sin-brain auto-sync to keep global and local brain in sync.",
    "",
    `BRAIN_CLI="${cliPath}"`,
    `BRAIN_ROOT="${brainRepoPath}"`,
    `PROJECT_ID="${projectId}"`,
    `SESSION_ID="${sessionId || "session-$(date +%s)"}"`,
    "",
    "# Extract knowledge from the session transcript (runs LLM extraction)",
    'node "$BRAIN_CLI" extract-knowledge \\',
    '  --root "$BRAIN_ROOT" \\',
    '  --project "$PROJECT_ID" \\',
    '  --session "$SESSION_ID" \\',
    "  2>/dev/null",
    "",
    "# Sync project brain bidirectionally",
    'if [ -n "$PROJECT_ROOT" ]; then',
    '  node "$BRAIN_CLI" sync \\',
    '    --root "$BRAIN_ROOT" \\',
    '    --project "$PROJECT_ID" \\',
    '    --project-root "$PROJECT_ROOT" \\',
    "    2>/dev/null",
    "fi",
    "",
    "# SIN-BRAIN: Auto-sync after every chat turn — no manual intervention needed",
    'node "$BRAIN_CLI" sync-chat-turn 2>/dev/null',
    "",
    "# SIN-BRAIN: Check if new rules were discovered and add them to global brain",
    'echo "[SIN-BRAIN] Auto-sync complete after chat turn."',
    "",
    'echo "PCPM_AFTERRUN_COMPLETE=true"',
    ""
  ].join("\n");
}

// Generate the PCPM-side configuration snippet that wires up the
// generated hook script paths and project metadata. This snippet is
// stored in .opencode/pcpm-config.json, not in OpenCode's schema file.
function generateOpenCodeConfig({ brainRepoPath, projectId, goalId, goalDescription, hooksDir }) {
  return {
    hooks: {
      beforeRun: path.join(hooksDir, "pcpm-before-run.sh"),
      afterRun: path.join(hooksDir, "pcpm-after-run.sh")
    },
    pcpm: {
      brainRepoPath,
      projectId,
      goalId,
      goalDescription,
      autoSync: true,
      extractKnowledge: true
    }
  };
}

async function mergeIntoProjectOpenCodeConfig(projectRoot, generatedConfig) {
  const configPath = path.join(projectRoot, ".opencode", "pcpm-config.json");
  const existingConfig = await readJsonFile(configPath, {});
  const mergedConfig = {
    ...existingConfig,
    hooks: {
      ...(existingConfig.hooks ?? {}),
      ...(generatedConfig.hooks ?? {}),
      onFailure: generatedConfig.hooks?.afterRun ?? existingConfig.hooks?.onFailure
    },
    pcpm: {
      ...(existingConfig.pcpm ?? {}),
      ...(generatedConfig.pcpm ?? {})
    },
    memory: {
      provider: "global-brain",
      requirePlan: true,
      requireActiveContext: true,
      requireForbidden: true
    },
    cli: {
      ...(existingConfig.cli ?? {}),
      command: "opencode",
      flags: ["--format", "json", "--non-interactive"]
    }
  };

  await writeJsonFile(configPath, mergedConfig);
  return {
    configPath,
    config: mergedConfig
  };
}

// Generate an AGENTS.md snippet that instructs agents to use PCPM context.
// This gets injected into the project's AGENTS.md to enforce brain usage.
function generateAgentsDirective({ projectId, goalDescription }) {
  return [
    "# PCPM (Persistent Code Plan Memory) Integration",
    "",
    "This project uses the global-brain PCPM system for persistent memory across sessions.",
    "",
    `**Project ID:** ${projectId}`,
    `**Current Goal:** ${goalDescription}`,
    "",
    "## Rules for All Agents",
    "",
    "1. Before starting work, load the active context from `.pcpm/active-context.json`",
    "2. Follow the current plan in `.pcpm/plan/latest.json` — do NOT improvise",
    "3. Never reuse strategies listed in the memory's `forbidden` entries",
    "4. After completing work, ensure knowledge is extracted and synced",
    "5. If the strategy must change, document the decision explicitly",
    "6. Check `.pcpm/knowledge-summary.json` for known mistakes before debugging",
    ""
  ].join("\n");
}

// Main function: set up PCPM hooks for a project.
// Creates hook scripts, generates the PCPM config, and optionally writes an AGENTS.md directive.
//
// This writes:
//   <projectRoot>/.opencode/hooks/pcpm-before-run.sh
//   <projectRoot>/.opencode/hooks/pcpm-after-run.sh
//   <projectRoot>/.opencode/pcpm-config.json (the PCPM config snippet)
export async function setupProjectHooks({
  projectRoot,
  brainRepoPath,
  projectId,
  goalId = "default-goal",
  goalDescription = "Continue development",
  sessionId = null,
  writeAgentsDirective = false
}) {
  const hooksDir = path.join(projectRoot, ".opencode", "hooks");
  await ensureDir(hooksDir);

  const beforeRunPath = path.join(hooksDir, "pcpm-before-run.sh");
  const afterRunPath = path.join(hooksDir, "pcpm-after-run.sh");
  const configPath = path.join(projectRoot, ".opencode", "pcpm-config.json");

  // Write the beforeRun hook script
  const { promises: fs } = await import("node:fs");

  const beforeRunContent = generateBeforeRunScript({
    brainRepoPath,
    projectId,
    goalId,
    goalDescription
  });
  await fs.writeFile(beforeRunPath, beforeRunContent, { mode: 0o755 });

  // Write the afterRun hook script
  const afterRunContent = generateAfterRunScript({
    brainRepoPath,
    projectId,
    sessionId
  });
  await fs.writeFile(afterRunPath, afterRunContent, { mode: 0o755 });

  // Write the config snippet
  const config = generateOpenCodeConfig({
    brainRepoPath,
    projectId,
    goalId,
    goalDescription,
    hooksDir
  });
  await writeJsonFile(configPath, config);
  const mergedProjectConfig = await mergeIntoProjectOpenCodeConfig(projectRoot, config);

  // Optionally write an AGENTS.md directive for the project
  let agentsDirectivePath = null;
  if (writeAgentsDirective) {
    agentsDirectivePath = path.join(projectRoot, ".opencode", "PCPM-AGENTS.md");
    const directive = generateAgentsDirective({ projectId, goalDescription });
    await fs.writeFile(agentsDirectivePath, directive, "utf8");
  }

  return {
    hooksDir,
    beforeRunScript: beforeRunPath,
    afterRunScript: afterRunPath,
    configFile: configPath,
    opencodeConfigFile: mergedProjectConfig.configPath,
    agentsDirective: agentsDirectivePath,
    config,
    mergedProjectConfig: mergedProjectConfig.config
  };
}

// Check if a project already has PCPM hooks set up.
// Returns the current config if found, null otherwise.
export async function detectExistingHooks(projectRoot) {
  const opencodeDir = path.join(projectRoot, ".opencode");
  const pcpmConfigPath = path.join(opencodeDir, "pcpm-config.json");

  if (!(await fileExists(pcpmConfigPath))) {
    return null;
  }

  return readJsonFile(pcpmConfigPath, null);
}
